# Generated by Django 5.2.8 on 2026-03-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Kích hoạt"),
        ),
    ]
