# Generated by Django 5.2.8 on 2026-03-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_voucher_cart_order_orderitem_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="engine",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="fuel_consumption",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="version_options",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
