# Generated by Django 5.2.8 on 2026-03-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_product_color_options_product_engine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
