# Generated by Django 5.2.8 on 2026-03-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_category_image_url_product_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="order",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partial", "Partial"),
                    ("paid", "Paid"),
                    ("pending_confirmation", "Pending Confirmation"),
                ],
                default="unpaid",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit 10%"),
                    ("full", "Full Payment"),
                    ("showroom", "Pay at Showroom"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
