# Generated by Django 5.2.8 on 2026-03-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_alter_order_status_returnrequest"),
        ("shops", "0008_notification"),
    ]

    operations = []
